#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

import sys
import zmq
import time
# minnow comms
from minnow_comms.minnow_app_multiprocess import App
# flatbuffer serialization
import flatbuffers
# generated by flatc
import topics.nav.imu
import topics.motor.command
# motor control library
from minnow_motor_control.HeadingControl import *
from minnow_motor_control.SurgeSpeedControl import *

class MotorControl(App):
    def __init__(self):
        super().__init__()
        self.setup_subscribers()
        # setup flatbuffers
        self.fb_builder = flatbuffers.Builder(1024)
        # setup motor controllers
        self.speed_control_system = speed_controller()
        self.heading_control_system = heading_controller()
        # variables
        self.nav_imu_msg = None

        # This is for standalone troubleshooting of the python code ---------------------
        self.desired_speed = 0.0
        self.desired_heading = 270     # between 0 - 360
        self.desired_pitch = 0.0

        self.current_speed = 0.0
        # self.current_heading = 170
        self.current_pitch = -2.0
        self.contrl_desired_heading = 0
        if (self.desired_heading >= 0) and (self.desired_heading <= 180):
            self.contrl_desired_heading = self.desired_heading
        else:
            self.contrl_desired_heading = self.desired_heading - 360
        # -------------------------------------------------------------------------------

    def setup_subscribers(self):
        self.subscribe('nav.imu', self.nav_imu_callback)    # subscribe to imu messages

    def nav_imu_callback(self, msg):
        self.nav_imu_msg = topics.nav.imu.imu.GetRootAsimu(msg, 0)

    def process(self):
        if self.nav_imu_msg is not None:
            current_heading = self.nav_imu_msg.Yaw()

        if (current_heading >= 0) and (current_heading <= 180):
            contrl_current_heading = current_heading
        else:
            contrl_current_heading = current_heading - 360
        print('current hdg',current_heading)
        #print('cntrl desi hdg',self.contrl_desired_heading)
        self.heading_control_system.DesiredHeading(self.contrl_desired_heading)

        # Run speed controller
        (speed_contrl_thrust)=self.speed_control_system.update(self.desired_speed)
        #print("Speed Control Thrust Output: %f" % (speed_contrl_thrust))
        # Run heading controller
        (hdg_differential_thrust,hdg_port_thrust,hdg_stbd_thrust)=self.heading_control_system.update(contrl_current_heading,speed_contrl_thrust)
        #print(hdg_differential_thrust)
        #print("Heading control port thrust: %f" % hdg_port_thrust)
        #print("Heading control stbd thrust: %f" % hdg_stbd_thrust)
        print('')

        topics.motor.command.commandStart(self.fb_builder)
        topics.motor.command.commandAddTime(self.fb_builder, time.time())
        topics.motor.command.commandAddMotor1Command(self.fb_builder, hdg_port_thrust)
        topics.motor.command.commandAddMotor2Command(self.fb_builder, hdg_stbd_thrust)
        motor_msg = topics.motor.command.commandEnd(self.fb_builder)
        self.fb_builder.Finish(motor_msg)
        bin_motor_msg = self.fb_builder.Output()
        self.publish(b'motor.command' + b' ' + bin_motor_msg)

        time.sleep(0.01)

if __name__ == "__main__":
    app = MotorControl()
    app.run()
