#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

import sys
import zmq
import time
import math
import signal
from collections import deque
from threading import Thread
import flatbuffers
#generated by flatc
import topics.nav.gps
#magnetic declination library
from geomag import geomag

class Subscriber(Thread):
    def __init__(self, context, id, topics_callbacks):
        super().__init__()
        self.context = context
        self.topics_callbacks = topics_callbacks
        self.loop = False

    def run(self):
        print('starting subscriber, on topic(s) {}'.format(self.topics_callbacks.keys()))
        subscriber = self.context.socket(zmq.SUB)
        subscriber.connect("tcp://127.0.0.1:5555")
        for topic in self.topics_callbacks.keys():
            subscriber.setsockopt_string(zmq.SUBSCRIBE, topic)
        poller = zmq.Poller()
        poller.register(subscriber, zmq.POLLIN)
        self.loop = True
        while self.loop:
            evts = poller.poll(1000)
            if evts:
                message = subscriber.recv()
                for topic in self.topics_callbacks.keys():
                    topic_name_msg = message.split(None,1)
                    topic_name = topic_name_msg[0]
                    topic_msg = topic_name_msg[1]
                    if topic == topic_name.decode('utf-8'):
                        self.topics_callbacks[topic](topic_msg)

    def stop(self):
        self.loop = False

class Publisher:
    def __init__(self):
        signal.signal(signal.SIGINT, self.exit_signal)
        self.zmq_context = zmq.Context()
        self.setup_subscriber()
        self.mag_declination = -14.42   #declination at MIT
        #setup flatbuffers
        self.fb_builder = flatbuffers.Builder(1024)
        #setup magnetic declination
        self.geomag = geomag.GeoMag()
        #setup gps
        self.latitude = 42.358456       #MIT coordinates
        self.longitude = -71.087589

    def exit_signal(self, sig, frame):
        print('You pressed Ctrl+C!')
        sys.exit(0)

    def setup_subscriber(self):
        # NO SUBSCRIPTIONS
        pass

    def run(self):
        socket = self.zmq_context.socket(zmq.PUB)
        socket.connect("tcp://127.0.0.1:5556")

        count = 0
        while True:
            count += 1

            topics.nav.gps.gpsStart(self.fb_builder)
            topics.nav.gps.gpsAddTime(self.fb_builder, time.time())

            #calculate magnetic declination
            mag = self.geomag.GeoMag(self.latitude, self.longitude)
            self.mag_declination = mag.dec
            topics.nav.gps.gpsAddMagDeclination(self.fb_builder, self.mag_declination)

            gps_msg = topics.nav.gps.gpsEnd(self.fb_builder)
            self.fb_builder.Finish(gps_msg)
            bin_gps_msg = self.fb_builder.Output()
            socket.send(b'nav.gps' + b' ' + bin_gps_msg)

            time.sleep(.01)

if __name__ == "__main__":
    pub = Publisher()
    pub.run()
